version: '2'
services:
  cakephp:
    build: .
    depends_on:
      - mysql
    links:
      - "mysql"
    ports:
      - "4000:80"  
    volumes:
      - .:/var/www/html/
    environment:
      - SECURITY_SALT=3f3f24274a6d9f60123af8c4d10ea65c8f04d8f76027f18f8be5141920f4853c
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=jwilcox
      - MYSQL_PASSWORD=password
  mysql:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    environment:      
      - MYSQL_DATABASE=cake_cms
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql-data:
